// R:\Art\models/spells\book

// This file generated by qdata - Do NOT Modify

#define FRAME_poly000         	0
#define FRAME_poly001         	1
#define FRAME_poly002         	2
#define FRAME_poly003         	3
#define FRAME_poly004         	4
#define FRAME_poly005         	5
#define FRAME_poly006         	6
#define FRAME_poly007         	7
#define FRAME_poly008         	8
#define FRAME_poly009         	9
#define FRAME_poly010         	10
#define FRAME_poly011         	11
#define FRAME_poly012         	12
#define FRAME_poly013         	13
#define FRAME_poly014         	14
#define FRAME_poly015         	15
#define FRAME_poly016         	16
#define FRAME_poly017         	17
#define FRAME_poly018         	18
#define FRAME_poly019         	19
#define FRAME_poly020         	20
#define FRAME_poly021         	21
#define FRAME_poly022         	22
#define FRAME_poly023         	23
#define FRAME_poly024         	24
#define FRAME_poly025         	25
#define FRAME_poly026         	26
#define FRAME_poly027         	27
#define FRAME_poly028         	28
#define FRAME_poly029         	29
#define FRAME_poly030         	30
#define FRAME_test            	31

#define MODEL_SCALE		1.000000

#define NUM_MESH_NODES		1

#define MESH_DEFAULT		0
