#ifndef G_BOUNDINGFORM_H
#define G_BOUNDINGFORM_H

#include "q_Typedef.h"

// sides for a nonrotating box
enum Box_BoundingForm_Sides_t
{
	BOX_BOUNDINGFORM_SIDE_WEST,
	BOX_BOUNDINGFORM_SIDE_NORTH,
	BOX_BOUNDINGFORM_SIDE_SOUTH,
	BOX_BOUNDINGFORM_SIDE_EAST,
	BOX_BOUNDINGFORM_SIDE_BOTTOM,
	BOX_BOUNDINGFORM_SIDE_TOP,
	NUM_BOX_BOUNDINGFORM_SIDES
} ;

#endif // G_BOUNDINGFORM_H