// r:\base\models/monsters\spreader\bomb

// This file generated by qdata - Do NOT Modify

#define FRAME_bomb            	0

#define MODEL_SCALE		1.000000

#define NUM_MESH_NODES		1

#define MESH_BOMBASE		0
