// R:\Art\models/objects\feathers\feather2

// This file generated by qdata - Do NOT Modify

#define FRAME_poly            	0

#define MODEL_SCALE		1.000000

#define NUM_MESH_NODES		1

#define MESH_DEFAULT		0
